name: j-rn
inputs:
  github-token:
    description: Token with write access to this repo
    required: true
  task:
    description: Task(s) to perform (auto/check/build/deploy/comment)
    required: false
    default: auto
  deploy-branch:
    description: Branch for rendering HTML
    required: false
    default: gh-pages
  ignore-errors:
    description: Convert errors to warnings
    required: false
    default: ''
  python:
    description: Python executable
    required: false
    default: python
runs:
  using: composite
  steps:
  - name: make
    run: |
      export TASK="${TASK//,/ }"  # strip commas
      if [[ $GITHUB_EVENT_NAME == push || $GITHUB_EVENT_NAME == pull_request ]]; then
        if [[ "$GITHUB_REF" == "refs/tags"* ]]; then
          export TASK="${TASK//auto/deploy}"
        else
          export TASK="${TASK//auto/check build}"
        fi
      elif [[ $GITHUB_EVENT_NAME == *_comment ]]; then
        export TASK="${TASK//auto/comment}"
      fi
      make -f "${{ github.action_path }}/action.Makefile" $TASK
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      TASK: ${{ inputs.task }}
      IGNORE_ERRORS: ${{ inputs.ignore-errors }}
      DEPLOY_BRANCH: ${{ inputs.deploy-branch }}
      PYTHON: ${{ inputs.python }}
      GIT_AUTHOR_NAME: J-RN[bot]
      GIT_AUTHOR_EMAIL: 80856664+j-rn-bot@users.noreply.github.com
branding:
  icon: book-open
  color: orange
