# -*- coding: utf-8 -*-
# For a full list of options see http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------
project = "The J-RN"
from meta import authors, copyright_code, copyright_text, description, release, title, version, year

_auths = ["{lastname}, {forenames}".format(**i) for i in authors]
_auths_links = [
    j if 'orcid' not in i else '<a href="https://orcid.org/{orcid}">{j}</a>'.format(j=j, **i)
    for i, j in zip(authors, _auths)]
author = _auths_links[0] if len(
    _auths_links) < 2 else f'{"; ".join(_auths_links[:-1])}, and {_auths_links[-1]}'
copyright = f'{year} <a href="https://spdx.org/licenses/{copyright_text}.html">{copyright_text}</a> (text) <a href="https://spdx.org/licenses/{copyright_code}.html">{copyright_code}</a> (code) {author}'

# -- General configuration ---------------------------------------------------
extensions = ['nbsphinx', 'sphinx.ext.mathjax', 'sphinx.ext.githubpages', 'sphinxcontrib.bibtex']
templates_path = ['_templates']
source_suffix = '.ipynb'
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------
html_theme = 'alabaster'
html_theme_options = {
    'github_user': os.getenv('GITHUB_REPOSITORY').split("/", 1)[0],
    'github_repo': os.getenv('GITHUB_REPOSITORY').split("/", 1)[1],
    'description': description,
}
html_static_path = ['_static']

# -- Options for HTMLHelp output ---------------------------------------------
# Output file base name for HTML help builder.
htmlhelp_basename = 'pagesdoc'

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '10pt',
    'figure_align': 'htbp'}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [(master_doc, title + '.tex', title, " and ".join(_auths), 'manual')]

# -- Options for manual page output ------------------------------------------
# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, title, title, [author], 1)]

# -- Options for Texinfo output ----------------------------------------------
# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [(master_doc, title, title, " and ".join(_auths), title, description, 'Miscellaneous'),]
